simulation:
  backend: sim_gz
  with_moveit: true
  with_rviz: true
  with_gz_gui: false
  spawn_sim_controllers: false
  use_sim_time: true
  world_file: ""
  robot_name: dual_nero
  z_offset: 0.0
  sim_control_hardware_plugin: gz_ros2_control/GazeboSimSystem
  sim_control_system_plugin: libgz_ros2_control-system.so
  sim_control_system_plugin_name: gz_ros2_control::GazeboSimROS2ControlPlugin
  sim_control_system_plugin_path: /opt/ros/humble/lib
