OK = "OK"
ALLOW_MOTION_DISABLED = "ALLOW_MOTION_DISABLED"
ARM_OFFLINE = "ARM_OFFLINE"
ARM_NOT_ENABLED = "ARM_NOT_ENABLED"
CURRENT_POSE_OUT_OF_LIMIT = "CURRENT_POSE_OUT_OF_LIMIT"
CURRENT_POSE_NEAR_LIMIT = "CURRENT_POSE_NEAR_LIMIT"
INVALID_GOAL_STRUCTURE = "INVALID_GOAL_STRUCTURE"
INVALID_JOINT_SET = "INVALID_JOINT_SET"
STATE_UNAVAILABLE = "STATE_UNAVAILABLE"
STATE_TOO_OLD = "STATE_TOO_OLD"
START_DEVIATION_TOO_LARGE = "START_DEVIATION_TOO_LARGE"

ALL_CODES = (
    OK,
    ALLOW_MOTION_DISABLED,
    ARM_OFFLINE,
    ARM_NOT_ENABLED,
    CURRENT_POSE_OUT_OF_LIMIT,
    CURRENT_POSE_NEAR_LIMIT,
    INVALID_GOAL_STRUCTURE,
    INVALID_JOINT_SET,
    STATE_UNAVAILABLE,
    STATE_TOO_OLD,
    START_DEVIATION_TOO_LARGE,
)
